/**
 * classic-DDIC / SE93 classrun bridge.
 *
 * ADT REST is GET-only for classic views (`VIEW/DV`) and transactions
 * (`TRAN/T`) — every mutating verb 405s (`ExceptionMethodNotSupported`); see
 * `./capabilities.ts`. SE11/SE93 write these objects through ordinary
 * function modules, so — like `./enhancement-bridge.ts` for BAdIs — this
 * module builds the `IF_OO_ADT_CLASSRUN` class source those objects are
 * deployed through: ABAP from a closed set of fragment generators (never by
 * concatenating caller input — see `./enhancement-templates.ts`), tagged so
 * the `out->write(...)` transcript can be parsed (function modules report
 * failure via `sy-subrc`, not exceptions).
 *
 * A third operation rides this bridge: `DEVC/K` (package)
 * create via `CL_PACKAGE_FACTORY` (see `./package-create.ts`). Unlike
 * `VIEW/DV`/`TRAN/T` (which 405), the blocker here is the CTS
 * transport-check pre-flight — full mechanism in that file's header.
 *
 * `IF_PACKAGE`'s methods (`./package-create.ts`, `./package-delete.ts`) raise
 * CLASSIC (non-`cx_root`) exceptions, same as `DDIF_VIEW_PUT` above — a
 * locked package short-dumped live through an unguarded
 * `lo_package->set_changeable( abap_true )` and destroyed the whole
 * transcript.
 */

import { AbapError } from "./errors.js";
import { ECHO_LINE_MAX, truncateForDisplay } from "../truncate.js";
import { assertPlainName, BRIDGE_PACKAGE } from "./run.js";

export { assertBridgeMutation, type BridgeMutationTarget } from "./bridge-mutation.js";
export {
  ABAP_SOURCE_LINE_MAX,
  assertDdicTranscript,
  DDIC_ERR_PREFIX,
  DDIC_NOTE_PREFIX,
  DDIC_TAGS,
  isHeadlessDynproFailure,
  parseDdicTranscript,
  type DdicTag,
  type DdicTranscript,
} from "./ddic-transcript.js";
import { ABAP_SOURCE_LINE_MAX, DDIC_ERR_PREFIX } from "./ddic-transcript.js";

/** Package the generated bridge class lives in — named separately from `BRIDGE_PACKAGE` so this file doesn't require cross-referencing run.ts, and so the two can diverge later. */
export const DDIC_BRIDGE_PACKAGE = BRIDGE_PACKAGE;

/**
 * Wrap `dataLines`/`bodyLines` in a minimal `IF_OO_ADT_CLASSRUN` class.
 *
 * `dataLines` are bare declarations (`ls_dd25v TYPE dd25v.`) with no leading
 * `DATA` keyword; this is the one place that prepends it — a real activation
 * failed when that assumption was wrong (see archive).
 *
 * Exported so each operation's test can run a generator/parser drift check
 * against the real emitted source.
 */
export function ddicBridgeSource(
  className: string,
  dataLines: readonly string[],
  bodyLines: readonly string[],
): string {
  const cls = assertPlainName(className, "Class name").toLowerCase();
  const data = dataLines.map((l) => `    DATA ${l}`).join("\n");
  const body = bodyLines.map((l) => `    ${l}`).join("\n");
  const source = `CLASS ${cls} DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS ${cls} IMPLEMENTATION.

  METHOD if_oo_adt_classrun~main.
*   Generated by abapsmith. Do not edit: this class is regenerated from
*   src/adt/ddic-bridge.ts whenever its content hash changes.
${data}
    TRY.
${body}
      CATCH cx_root INTO DATA(lx_err).
        out->write( |${DDIC_ERR_PREFIX} { lx_err->get_text( ) }| ).
    ENDTRY.
  ENDMETHOD.

ENDCLASS.
`;
  // Caught here, not at the server: a line over this fails the class-source PUT itself
  // (SEDI_ADT15/TooLongLine, live 2026-09-05) before DD_INDEX_INTERFACE or any other FM runs.
  source.split("\n").forEach((line, i) => {
    if (line.length > ABAP_SOURCE_LINE_MAX) {
      const excerpt = truncateForDisplay(line, ECHO_LINE_MAX);
      throw new AbapError(
        "CHECK_FAILED",
        `Generated bridge source line ${i + 1} is ${line.length} chars, over ABAP's ` +
          `${ABAP_SOURCE_LINE_MAX}-char class-source limit: ${excerpt}`,
        { line: i + 1, length: line.length, excerpt },
      );
    }
  });
  return source;
}

