/**
 * Per-call invoker classes (`ZCL_ZMCP_I_xxxxxxxx`, see `invoke.ts`) carry no
 * recoverable tool id in their own name — the hash deliberately excludes the
 * tool version, and the name alone doesn't encode the tool id either. The
 * only provenance is inside the generated source's comment and runtime
 * attach line, so counting/pruning invokers means listing the package,
 * reading each class, and parsing that text.
 */
import type { AbapConnection } from "../connection.js";
import type { SafetyGate } from "../../safety.js";
import { isAbapError, describeUnknownError } from "../errors.js";
import { resolveWriteTarget } from "../write.js";
import { FLUID_PACKAGE } from "./package.js";
import { deleteOneFluidObject } from "./delete.js";
import type { FluidLease } from "./retired.js";

/** Case-insensitive: ABAP class names are case-insensitive, and a hand-edited or server-echoed name may not come back uppercase. */
export const INVOKER_NAME_RE = /^ZCL_ZMCP_I_[0-9A-F]{8}$/i;

export interface FluidInvokerProvenance {
  readonly toolId?: string;
  readonly action?: string;
  readonly version?: string;
  readonly contract?: string;
}

const GENERATED_COMMENT_RE =
  /^\*\s*Generated by abapsmith for fluid tool '([^'\r\n]*)', action '([^'\r\n]*)'\.\s*Do not edit\.\s*$/im;
const ATTACH_LINE_RE =
  /zcl_zmcp_fluid_rt=>attach\(\s*io_out\s*=\s*out\s+iv_ver\s*=\s*'([^'\r\n]*)'\s+iv_contract\s*=\s*'([^'\r\n]*)'\s*\)/i;
const VERSION_RE = /^[0-9a-f]{8}$/;
const CONTRACT_RE = /^\d+\.\d+$/;

/**
 * Pure, best-effort text parse of an invoker's generated source — never
 * throws, and each field is present only when confidently parsed. Matches
 * `invokerSource`'s two marker lines in `invoke.ts` (the comment naming the
 * tool/action, and the `attach()` call naming version/contract) exactly, so
 * a hand-edited or truncated source just yields fewer fields rather than a
 * wrong answer.
 */
export function parseInvokerProvenance(source: string): FluidInvokerProvenance {
  const result: { toolId?: string; action?: string; version?: string; contract?: string } = {};

  const comment = GENERATED_COMMENT_RE.exec(source);
  if (comment) {
    result.toolId = comment[1];
    result.action = comment[2];
  }

  const attach = ATTACH_LINE_RE.exec(source);
  if (attach) {
    const version = attach[1] ?? "";
    const contract = attach[2] ?? "";
    if (VERSION_RE.test(version)) result.version = version;
    if (CONTRACT_RE.test(contract)) result.contract = contract;
  }

  return result;
}

/**
 * `ZCL_ZMCP_I_*` class names currently in `FLUID_PACKAGE`. Same node-listing
 * call as `removeTargets` in `src/tools/fluid.ts` (`conn.adt.nodeContents`,
 * the one `readPackage` in `ddic.ts` also uses) — only `CLAS/OC` members
 * whose name matches the invoker pattern.
 */
export async function listInvokerClasses(conn: AbapConnection): Promise<readonly string[]> {
  const listed = await conn.adt.nodeContents("DEVC/K", FLUID_PACKAGE);
  const names: string[] = [];
  for (const n of listed.nodes ?? []) {
    const name = n.OBJECT_NAME ?? "";
    const type = n.OBJECT_TYPE ?? "";
    if (!name || type !== "CLAS/OC") continue;
    if (INVOKER_NAME_RE.test(name)) names.push(name);
  }
  return names;
}

export interface FluidInvokerProbe {
  readonly name: string;
  readonly toolId?: string;
  readonly action?: string;
  readonly version?: string;
  readonly error?: string;
}

/**
 * Reads each named class's source and attaches its parsed provenance.
 * Addresses the class the same way `probeRetiredBridges` (`retired.ts`)
 * does — `resolveWriteTarget` — rather than building a source URI by hand;
 * its `sourceUri` (main include) is then read directly, same GET
 * `readSource` (`source.ts`) issues internally, since `resolveWriteTarget`'s
 * `ResolvedTarget` doesn't carry the extra fields `readSource` requires.
 * Best effort per class: a resolve or read failure records `error` and
 * never throws, so one bad class doesn't blind the rest of the probe.
 */
export async function probeInvokers(
  conn: AbapConnection,
  names: readonly string[],
): Promise<readonly FluidInvokerProbe[]> {
  const probes: FluidInvokerProbe[] = [];
  for (const name of names) {
    try {
      const resolved = await resolveWriteTarget(conn, { type: "CLAS/OC", name }, "delete");
      if (!resolved.exists) {
        probes.push({ name, error: "does not exist" });
        continue;
      }
      const resp = await conn.get(resolved.sourceUri, { headers: { Accept: "text/plain" } });
      const provenance = parseInvokerProvenance(resp.body);
      probes.push({ name, toolId: provenance.toolId, action: provenance.action, version: provenance.version });
    } catch (e) {
      probes.push({ name, error: describeUnknownError(e) });
    }
  }
  return probes;
}

/**
 * An invoker is stale for `toolId`/`currentVersion` only when its parsed
 * `toolId` matches AND it carries a parsed `version` that differs from
 * `currentVersion`. No parsed version, a different tool, or an unattributable
 * probe (parse or read failure) is never stale — pruning something we
 * cannot attribute risks deleting an object that isn't ours.
 */
export function staleInvokers(
  probes: readonly FluidInvokerProbe[],
  toolId: string,
  currentVersion: string,
): readonly FluidInvokerProbe[] {
  return probes.filter((p) => p.toolId === toolId && p.version !== undefined && p.version !== currentVersion);
}

export interface FluidInvokerPrune {
  readonly name: string;
  readonly outcome: "deleted" | "already-absent" | "failed";
  readonly error?: string;
}

/**
 * Deletes the given invokers, one lease per delete — same reason as
 * `reapRetiredBridges` (`retired.ts`): a delete kills the ADT session, and
 * `LOGON_ENDPOINT_LIFETIME_CEILING` is per connection instance, so a loop on
 * one connection dies after a handful of deletes. `NOT_FOUND` is
 * `already-absent`, not a failure; nothing here throws out of the loop.
 */
export async function pruneInvokers(
  gate: SafetyGate,
  lease: FluidLease,
  probes: readonly FluidInvokerProbe[],
): Promise<readonly FluidInvokerPrune[]> {
  const results: FluidInvokerPrune[] = [];
  for (const probe of probes) {
    try {
      const del = await lease("abap_fluid.repair.prune-invoker", (conn) =>
        deleteOneFluidObject(conn, gate, { type: "CLAS/OC", name: probe.name }, false),
      );
      results.push({ name: probe.name, outcome: del.deleted === false ? "failed" : "deleted" });
    } catch (e) {
      if (isAbapError(e) && e.code === "NOT_FOUND") {
        results.push({ name: probe.name, outcome: "already-absent" });
      } else {
        results.push({ name: probe.name, outcome: "failed", error: describeUnknownError(e) });
      }
    }
  }
  return results;
}
